services:
  app:
    image: node:18-alpine
    container_name: ai-image-generator
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app/:/app
    # command: sh -c "yarn create react-app ."
    # command: sh -c "yarn install && yarn start"
    command: sh -c "yarn start"